spec-version: 0.36.0
name: skm
version: 0.1.0
synopsis: Tool for the SKM language
author: Alexandra Zaldivar Aiello
github: lexzaiello/sk-lean
category: Language

ghc-options: -Wall -fno-warn-incomplete-uni-patterns

dependencies:
  - base >= 4.14 && < 5
  - optparse-applicative >= 0.14.3.0
  - megaparsec == 9.7.0

library:
  source-dirs: src
  exposed-modules:
    - Skm.Ast
    - Skm.Eval
    - Skm.Parse
    - Skm.Std

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - skm
